"use client";
import "./globals.css";
import { Montserrat } from "next/font/google";
import NavBar from "../components/Navbar";
import { store } from "@/redux/store";
import { Provider } from "react-redux";
import { useSelector } from "react-redux";

const montserrat = Montserrat({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
  variable: "--font-montserrat",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Provider store={store}>
        <body className={`${montserrat.className}`}>
          <NavBar />
          <main>
            {children}
            </main>
        </body>
      </Provider>
    </html>
  );
}
